const initialState = {
    url: localStorage.getItem("apiUrl"),
}

const url = [   {type:'URL_1', url:'http://localhost:8000/Al-Fatihah'},
                {type:'URL_2', url:'http://localhost:8000/Al-Baqarah'},
                {type:'URL_3', url:'http://localhost:8000/Ali-%60Imran'},
                {type:'URL_4', url:'http://localhost:8000/An-Nisa%60'},
                {type:'URL_5', url:'http://localhost:8000/Al-Ma%60idah'},
                {type:'URL_6', url:'http://localhost:8000/Al-An%60am'},
                {type:'URL_7', url:'http://localhost:8000/Al-A%60raf'},
                {type:'URL_8', url:'http://localhost:8000/Al-Anfal'},
                {type:'URL_9', url:'http://localhost:8000/At-Taubah'},
                {type:'URL_10', url:'http://localhost:8000/Yunus'},
                {type:'URL_11', url:'http://localhost:8000/Hud'},
                {type:'URL_12', url:'http://localhost:8000/Yusuf'},
                {type:'URL_13', url:'http://localhost:8000/Ar-Ra%60d'},
                {type:'URL_14', url:'http://localhost:8000/Ibrahim'},
                {type:'URL_15', url:'http://localhost:8000/Al-Hijr'},
                {type:'URL_16', url:'http://localhost:8000/An-Nahl'},
                {type:'URL_17', url:'http://localhost:8000/Al-Isra`'},
                {type:'URL_18', url:'http://localhost:8000/Al-Kahf'},
                {type:'URL_19', url:'http://localhost:8000/Maryam'},
                {type:'URL_20', url:'http://localhost:8000/Ta-Ha'},
                {type:'URL_21', url:'http://localhost:8000/Al-Anbiya'},
                {type:'URL_22', url:'http://localhost:8000/Al-Hajj'},
                {type:'URL_23', url:'http://localhost:8000/Al-Mu`minun'},
                {type:'URL_24', url:'http://localhost:8000/An-Nur'},
                {type:'URL_25', url:'http://localhost:8000/Al-Furqan'},
                {type:'URL_26', url:'http://localhost:8000/Asy-Syu`ara`'},
                {type:'URL_27', url:'http://localhost:8000/An-Naml'},
                {type:'URL_28', url:'http://localhost:8000/Al-Qasas'},
                {type:'URL_29', url:'http://localhost:8000/Al-`Ankabut'},
                {type:'URL_30', url:'http://localhost:8000/Ar-Rum'},
                {type:'URL_31', url:'http://localhost:8000/Luqman'},
                {type:'URL_32', url:'http://localhost:8000/As-Sajdah'},
                {type:'URL_33', url:'http://localhost:8000/Al-Ahzab'},
                {type:'URL_34', url:'http://localhost:8000/Saba`'},
                {type:'URL_35', url:'http://localhost:8000/Fatir'},
                {type:'URL_36', url:'http://localhost:8000/Ya-Sin'},
                {type:'URL_37', url:'http://localhost:8000/As-Saffat'},
                {type:'URL_38', url:'http://localhost:8000/Sad'},
                {type:'URL_39', url:'http://localhost:8000/Az-Zumar'},
                {type:'URL_40', url:'http://localhost:8000/Ghafir'},
                {type:'URL_41', url:'http://localhost:8000/Fussilat'},
                {type:'URL_42', url:'http://localhost:8000/Asy-Syura'},
                {type:'URL_43', url:'http://localhost:8000/Az-Zukhruf'},
                {type:'URL_44', url:'http://localhost:8000/Ad-Dukhan'},
                {type:'URL_45', url:'http://localhost:8000/Al-Jasiyah'},
                {type:'URL_46', url:'http://localhost:8000/Al-Ahqaf'},
                {type:'URL_47', url:'http://localhost:8000/Muhammad'},
                {type:'URL_48', url:'http://localhost:8000/Al-Fath'},
                {type:'URL_49', url:'http://localhost:8000/Al-Hujurat'},
                {type:'URL_50', url:'http://localhost:8000/Qaf'},
                {type:'URL_51', url:'http://localhost:8000/Az-Zariyat'},
                {type:'URL_52', url:'http://localhost:8000/At-Tur'},
                {type:'URL_53', url:'http://localhost:8000/An-Najm'},
                {type:'URL_54', url:'http://localhost:8000/Al-Qamar'},
                {type:'URL_55', url:'http://localhost:8000/Ar-Rahman'},
                {type:'URL_56', url:'http://localhost:8000/Al-Waqi`ah'},
                {type:'URL_57', url:'http://localhost:8000/Al-Hadid'},
                {type:'URL_58', url:'http://localhost:8000/Al-Mujadilah'},
                {type:'URL_59', url:'http://localhost:8000/Al-Hasyr'},
                {type:'URL_60', url:'http://localhost:8000/Al-Mumtahanah'},
                {type:'URL_61', url:'http://localhost:8000/As-Saff'},
                {type:'URL_62', url:'http://localhost:8000/Al-Jumu`ah'},
                {type:'URL_63', url:'http://localhost:8000/Al-Munafiqun'},
                {type:'URL_64', url:'http://localhost:8000/At-Taghabun'},
                {type:'URL_65', url:'http://localhost:8000/At-Talaq'},
                {type:'URL_66', url:'http://localhost:8000/At-Tahrim'},
                {type:'URL_67', url:'http://localhost:8000/Al-Mulk'},
                {type:'URL_68', url:'http://localhost:8000/Al-Qalam'},
                {type:'URL_69', url:'http://localhost:8000/Al-Haqqah'},
                {type:'URL_70', url:'http://localhost:8000/Al-Ma`arij'},
                {type:'URL_71', url:'http://localhost:8000/Nuh'},
                {type:'URL_72', url:'http://localhost:8000/Al-Jinn'},
                {type:'URL_73', url:'http://localhost:8000/Al-Muzzammil'},
                {type:'URL_74', url:'http://localhost:8000/An-Muddassir'},
                {type:'URL_75', url:'http://localhost:8000/Al-Qiyamah'},
                {type:'URL_76', url:'http://localhost:8000/Al-Insan'},
                {type:'URL_77', url:'http://localhost:8000/Al-Mursalat'},
                {type:'URL_78', url:'http://localhost:8000/An-Naba`'},
                {type:'URL_79', url:'http://localhost:8000/An-Nazi`at'},
                {type:'URL_80', url:'http://localhost:8000/`Abasa'},
                {type:'URL_81', url:'http://localhost:8000/At-Takwir'},
                {type:'URL_82', url:'http://localhost:8000/Al-Infitar'},
                {type:'URL_83', url:'http://localhost:8000/Al-Muthaffifiin'},
                {type:'URL_84', url:'http://localhost:8000/Al-Insyiqaq'},
                {type:'URL_85', url:'http://localhost:8000/Al-Buruj'},
                {type:'URL_86', url:'http://localhost:8000/At-Tariq'},
                {type:'URL_87', url:'http://localhost:8000/As-A`la'},
                {type:'URL_88', url:'http://localhost:8000/Al-Ghasyiyah'},
                {type:'URL_89', url:'http://localhost:8000/Al-Fajr'},
                {type:'URL_90', url:'http://localhost:8000/Al-Balad'},
                {type:'URL_91', url:'http://localhost:8000/Asy-Syams'},
                {type:'URL_92', url:'http://localhost:8000/Al-Lail'},
                {type:'URL_93', url:'http://localhost:8000/Ad-Duha'},
                {type:'URL_94', url:'http://localhost:8000/Al-Insyirah'},
                {type:'URL_95', url:'http://localhost:8000/At-Tin'},
                {type:'URL_96', url:'http://localhost:8000/Al-`Alaq'},
                {type:'URL_97', url:'http://localhost:8000/Al-Qadr'},
                {type:'URL_98', url:'http://localhost:8000/Al-Bayyinah'},
                {type:'URL_99', url:'http://localhost:8000/Az-Zalzalah'},
                {type:'URL_100', url:'http://localhost:8000/Al-`Adiyat'},
                {type:'URL_101', url:'http://localhost:8000/Al-Qari`ah'},
                {type:'URL_102', url:'http://localhost:8000/At-Takasur'},
                {type:'URL_103', url:'http://localhost:8000/Al-`Asr'},
                {type:'URL_104', url:'http://localhost:8000/Al-Humazah'},
                {type:'URL_105', url:'http://localhost:8000/Al-Fil'},
                {type:'URL_106', url:'http://localhost:8000/Quraisy'},
                {type:'URL_107', url:'http://localhost:8000/Al-Ma`un'},
                {type:'URL_108', url:'http://localhost:8000/Al-Kausar'},
                {type:'URL_109', url:'http://localhost:8000/Al-Kafirun'},
                {type:'URL_110', url:'http://localhost:8000/An-Nasr'},
                {type:'URL_111', url:'http://localhost:8000/Al-Lahab'},
                {type:'URL_112', url:'http://localhost:8000/Al-Ikhlas'},
                {type:'URL_113', url:'http://localhost:8000/Al-Falaq'},
                {type:'URL_114', url:'http://localhost:8000/An-Nas'},
            ]
const api = (state = initialState, action) => {
    const newUrl = {...state};

    url.map(urls =>{
        if (action.type === urls.type) {
            newUrl.url = urls.url
            localStorage.setItem("apiUrl", newUrl.url)
        }    
    })

    return newUrl
}

export default api